# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corC <- function(x, y) {
    .Call('_fast_EOT_corC', PACKAGE = 'fast.EOT', x, y)
}

fastCor <- function(x_i, y_i, standardised) {
    .Call('_fast_EOT_fastCor', PACKAGE = 'fast.EOT', x_i, y_i, standardised)
}

lmC <- function(x, y) {
    .Call('_fast_EOT_lmC', PACKAGE = 'fast.EOT', x, y)
}

respLmParam <- function(x, y, cell) {
    .Call('_fast_EOT_respLmParam', PACKAGE = 'fast.EOT', x, y, cell)
}

